id: wordpress-wpconfig-inclosure

info:
  name: Wordpress wpconfig disclosure
  author: zhizhuo
  severity: high
  verified: true
  description: |
    Wordpress wpconfig.php 文件包含漏洞，攻击者可以通过构造特殊的请求参数，包含服务器上的任意文件。
    fofa: app="Wordpress"
  tags: wordpress,wpconfig,inclosure
  created: 2025/03/13

rules:
  r0:
    request:
      method: GET
      path: /wp-config.php.save
    expression: response.status == 200 && response.body.bcontains(b'define') && response.body.bcontains(b'SECURE_AUTH_KEY')
expression: r0()
